apiVersion: batch/v1
kind: Job
metadata:
  name: pi-calculator
spec:
  template:
    spec:
      containers:
      - name: pi-calculator
        image: perl:5.34.0
        command: ["perl", "-Mbignum=bpi", "wle"]
      restartPolicy: Never
  completions: 1